/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.flexbox;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name = "TiFlexbox", id = "ti.flexbox")
public class TiFlexboxModule extends KrollModule {

    // Standard Debugging variables
    private static final String LCAT = "TiFlexboxModule";
    private static final boolean DBG = TiConfig.LOGD;


    public TiFlexboxModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }


}

